name: HouDocker Autobuild

on:
  schedule:
    - cron: '0 0 */1 * *' # Run every day at midnight
  workflow_dispatch:

jobs:
  autobuild:
    runs-on: ubuntu-latest
    env:
      SIDEFX_CLIENT: ${{secrets.SIDEFX_CLIENT}}
      SIDEFX_SECRET: ${{secrets.SIDEFX_SECRET}}
      DOCKER_USER: ${{secrets.DOCKER_USER}}
      DOCKER_SECRET: ${{secrets.DOCKER_SECRET}}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./hbuild/requirements.txt
    - name: Run autobuild.py
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        export DOCKER_DEFAULT_PLATFORM="linux/amd64"
        python ./hbuild/autobuild.py